id: cmd:BUILD
name: BUILD
syntax: CMD:BUILD
module_id: module:A
description: Command (auto-extracted)
examples:
- 'EXPECT_EXPAND: CMD:FIX;AUTO:Y|CMD:BUILD;ENV:PROD'
stability: stable
mcp_exposed: true
aliases:
- BUILD
token_cost_hint: 1
text_compact: '[COMMAND] CMD:BUILD (A, stable)

  Intent: Command (auto-extracted)

  Syntax: CMD:BUILD'
keywords:
- cmd
