id: cmd:TRAIN
name: TRAIN
syntax: CMD:TRAIN
module_id: module:E
description: Trainieren
examples:
- CMD:PREP;CMD:FEAT;NORM:STD;CMD:TRAIN;MDL:XGB;SPLIT:CV5;CMD:EVAL;METR:F1,AUC
- CMD:TRAIN,PRED,EVAL,PREP,FEAT
- CMD:PREP;NORM:STD;CMD:TRAIN;MDL:RF,XGB;SPLIT:CV5;METR:ACC,F1;CMD:PLOT;GRPH:BAR
- 'pipeline": "CMD:PREP;SRC:$input→CMD:TRAIN;MDL:RF→CMD:PLOT;TYP:CONF→CMD:REP;FMT:MD",'
- STEP:CMD:TRAIN;MDL:RF;FB:MDL:LR;TIMEOUT:300,
- CMD:PREP;SRC:CSV;EDA:Y;CLEAN:MV,OUT,ENC|CMD:FEAT;SCALE:Y;SELECT:Y|CMD:TRAIN;MDL:RF,XGB,LR;CV:5;HPT:Y|CMD:EVAL;METRIC:ACC,PREC,REC,F1,AUC;PLOT:CONF,FIMP|CMD:SAVE;FMT:PKL|CMD:REP;FMT:MD
- CMD:PREP;SRC:CSV;CLEAN:Y|CMD:TRAIN;MDL:RF;EVAL:Y→CMD:PLOT;TYP:CONF;FMT:PNG→CMD:REP;FMT:MD
- CMD:TRAIN;MDL:XGB;HPT:Y→CMD:ETL;SRC:S3;DST:PG|CMD:PIPE;TOOL:GHA;STG:PROD|CMD:TEST;TYP:INTEG;ENV:PROD
stability: stable
mcp_exposed: true
aliases:
- TRAIN
token_cost_hint: 1
text_compact: '[COMMAND] CMD:TRAIN (E, stable)

  Intent: Trainieren

  Syntax: CMD:TRAIN'
keywords:
- cmd
