"""Token reduction measurement utilities for natural language and CompText commands."""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence

try:
    import tiktoken

    TIKTOKEN_AVAILABLE = True
except ImportError:
    TIKTOKEN_AVAILABLE = False

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class TokenReductionCase:
    """Represents a single token reduction scenario."""

    name: str
    original: str
    comptext: str


DEFAULT_CASES: Sequence[TokenReductionCase] = (
    TokenReductionCase(
        name="Code Optimization",
        original=(
            "Please analyze this Python code, identify performance bottlenecks, "
            "suggest optimizations with code examples, explain the reasoning behind "
            "each optimization, and provide benchmark comparisons showing expected "
            "improvements"
        ),
        comptext=(
            "@CODE_ANALYZE[perf_bottleneck] + "
            "@CODE_OPT[explain=detail, bench=compare]"
        ),
    ),
    TokenReductionCase(
        name="Marketing Plan",
        original=(
            "Generate a comprehensive marketing plan with budget breakdown, timeline, "
            "channels, KPIs, and risk mitigation steps."
        ),
        comptext="@PLAN[marketing, include=budget+timeline+channels+KPIs+risk]",
    ),
    TokenReductionCase(
        name="CI Pipeline",
        original=(
            "Explain how to set up a CI pipeline using GitHub Actions with linting, "
            "tests, and deployment steps."
        ),
        comptext="@CI_PIPELINE[gha, steps=lint+test+deploy]",
    ),
)


def token_count(text: str, model: str = "cl100k_base") -> int:
    """Return a precise token count using tiktoken (OpenAI/Anthropic standard).

    Falls back to robust regex counting if tiktoken is not installed.
    """
    if not text:
        return 0
    if TIKTOKEN_AVAILABLE:
        try:
            encoding = tiktoken.get_encoding(model)
            return len(encoding.encode(text))
        except Exception as e:
            logger.warning("Tiktoken error: %s. Falling back to regex.", e)

    # Robust Fallback: words AND punctuation separately
    # Note: This is an approximation; results may differ from TikToken.
    return len(re.findall(r"\w+|[^\w\s]", text, re.UNICODE))


def calculate_reduction(
    name: str, original: str, comptext: str
) -> dict[str, Any]:
    """Calculate token reduction metrics for a single case."""
    original_tokens = token_count(original)
    comptext_tokens = token_count(comptext)
    reduction = max(original_tokens - comptext_tokens, 0)
    reduction_pct = (
        round((reduction / original_tokens) * 100, 1)
        if original_tokens > 0
        else 0.0
    )

    return {
        "name": name,
        "original_tokens": original_tokens,
        "comptext_tokens": comptext_tokens,
        "token_reduction": reduction,
        "reduction_pct": reduction_pct,
    }


def generate_markdown_report(cases: Iterable[TokenReductionCase]) -> str:
    """Generate a markdown table summarizing token reductions."""
    metrics: list[dict[str, Any]] = [
        calculate_reduction(case.name, case.original, case.comptext)
        for case in cases
    ]
    lines = [
        "# Token Reduction Results",
        "",
        "| Case | Original Tokens | CompText Tokens | Reduction | Reduction % |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]

    for metric in metrics:
        lines.append(
            f"| {metric['name']} | {metric['original_tokens']} | "
            f"{metric['comptext_tokens']} | {metric['token_reduction']} | "
            f"{metric['reduction_pct']} |"
        )

    lines.append("")
    lines.append(
        "Generated by the token reduction helper script "
        "using deterministic sample prompts."
    )
    return "\n".join(lines)


def write_report(report_path: Path, content: str) -> None:
    """Write the report content to the given path."""
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(content, encoding="utf-8")


def main(output_path: Path | None = None) -> None:
    """Entry point for running the token reduction suite."""
    report_content = generate_markdown_report(DEFAULT_CASES)
    target = output_path or Path.cwd() / "TOKEN_REDUCTION_RESULTS.md"
    write_report(target, report_content)
    print(f"✅ Token reduction report written to {target}")


if __name__ == "__main__":
    main()
