profiles:
  - name: default
    description: Default CompText profile with all modules enabled
    enabled_modules:
      - A
      - B
      - C
    default_settings:
      compression_level: medium
      analysis_depth: standard

  - name: minimal
    description: Minimal profile with only core commands
    enabled_modules:
      - A
    default_settings:
      compression_level: high
